export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"



export const SIGNUP_REQUEST="SIGNUP_REQUEST"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const SIGNUP_FAILURE="SIGNUP_FAILURE"


export const LOGOUT_REQUEST="LOGOUT_RAQUEST"

export const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST"
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE"

export const GET_OTP_REQUEST="GET_OTP_REQUEST"
export const GET_OTP_SUCCESS="GET_OTP_SUCCESS"
export const GET_OTP_FAILURE="GET_OTP_FAILURE"


export const VERIFY_OTP_REQUEST="VERIFY_OTP_REQUEST"
export const VERIFY_OTP_SUCCESS="VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_FAILURE="VERIFY_OTP_FAILURE"


export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAILURE="RESET_PASSWORD_FAILURE"


export const EDIT_PROFILE_REQUEST="EDIT_PROFILE_REQUEST"
export const EDIT_PROFILE_SUCCESS="EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAILURE="EDIT_PROFILE_FAILURE"



