export const GET_ALL_VIDEOS_REQUEST = "GET_ALL_VIDEOS";
export const GET_ALL_VIDEOS_SUCCESS = "GET_ALL_VIDEOS_SUCCESS";
export const GET_ALL_VIDEOS_FAILURE = "GET_ALL_VIDEOS_FAILURE";

export const FILTER_UPLOADED_VIDEOS = "FILTER_UPLOADED_VIDEOS";

export const FILTER_FAVOURITE_VIDEOS = "FILTER_FAVOURITE_VIDEOS";

export const GET_VIDEO_BY_ID_REQUEST = "GET_VIDEO_BY_ID_REQUEST";
export const GET_VIDEO_BY_ID_SUCCESS = "GET_VIDEO_BY_ID_SUCCESS";
export const GET_VIDEO_BY_ID_FAILURE = "GET_VIDEO_BY_ID_FAILURE";

export const ADD_TO_FAVOURITE_REQUEST = "ADD_TO_FAVOURITE_REQUEST";
export const ADD_TO_FAVOURITE_SUCCESS = "ADD_TO_FAVOURITE_SUCCESS";
export const ADD_TO_FAVOURITE_FAILURE = "ADD_TO_FAVOURITE_FAILURE";

export const GET_FAVOURITE_REQUEST = "GET_FAVOURITE_REQUEST";
export const GET_FAVOURITE_SUCCESS = "GET_FAVOURITE_SUCCESS";
export const GET_FAVOURITE_FAILURE = "GET_FAVOURITE_FAILURE";

export const CHEF_REQUEST = "CHEF_REQUEST";
export const CHEF_SUCCESS = "CHEF_SUCCESS";
export const CHEF_FAILURE = "CHEF_FAILURE";

export const REMOVE_FAVOURITE_REQUEST = "REMOVE_FAVOURITE_REQUEST";
export const REMOVE_FAVOURITE_SUCCESS = "REMOVE_FAVOURITE_SUCCESS";
export const REMOVE_FAVOURITE_FAILURE = "REMOVE_FAVOURITE_FAILURE";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";

export const GET_CHEF_BY_ID_REQUEST = "GET_CHEF_BY_ID_REQUEST";
export const GET_CHEF_BY_ID_SUCCESS = "GET_CHEF_BY_ID_SUCCESS";
export const GET_CHEF_BY_ID_FAILURE = "GET_CHEF_BY_ID_FAILURE";

export const SEARCH_VIDEO_FILTER = "SEARCH_VIDEO_FILTER";

export const SEARCH_FILTER = "SEARCH_FILTER";

export const SUBMIT_RATING_REQUEST = "SUBMIT_RATING_REQUEST";
export const SUBMIT_RATING_SUCCESS = "SUBMIT_RATING_SUCCESS";
export const SUBMIT_RATING_FAILURE = "SUBMIT_RATING_FAILURE";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAILURE = "COMMENT_FAILURE";
