
export const GET_ALL_VIDEOS_REQUEST="GET_ALL_VIDEOS"
export const GET_ALL_VIDEOS_SUCCESS="GET_ALL_VIDEOS_SUCCESS"
export const GET_ALL_VIDEOS_FAILURE="GET_ALL_VIDEOS_FAILURE"

export const FILTER_UPLOADED_VIDEOS="FILTER_UPLOADED_VIDEOS"

export const GET_VIDEO_BY_ID_REQUEST="GET_VIDEO_BY_ID_REQUEST"
export const GET_VIDEO_BY_ID_SUCCESS="GET_VIDEO_BY_ID_SUCCESS"
export const GET_VIDEO_BY_ID_FAILURE="GET_VIDEO_BY_ID_FAILURE"



export const ADD_TO_FAVOURITE_REQUEST="ADD_TO_FAVOURITE_REQUEST"
export const ADD_TO_FAVOURITE_SUCCESS="ADD_TO_FAVOURITE_SUCCESS"
export const ADD_TO_FAVOURITE_FAILURE="ADD_TO_FAVOURITE_FAILURE"


export const GET_FAVOURITE_REQUEST="GET_FAVOURITE_REQUEST"
export const GET_FAVOURITE_SUCCESS="GET_FAVOURITE_SUCCESS"
export const GET_FAVOURITE_FAILURE="GET_FAVOURITE_FAILURE"


export const REMOVE_FAVOURITE_REQUEST="REMOVE_FAVOURITE_REQUEST"
export const REMOVE_FAVOURITE_SUCCESS="REMOVE_FAVOURITE_SUCCESS"
export const REMOVE_FAVOURITE_FAILURE="REMOVE_FAVOURITE_FAILURE"






