export const CHEF_REQUEST="CHEF_REQUEST"

export const CHEF_SUCCESS="CHEF_SUCCESS"

export const CHEF_FAILURE="CHEF_FAILURE"



export const GET_CHEF_WITH_ID_REQUEST="GET_CHEF_WITH_ID_REQUEST"
export const GET_CHEF_WITH_ID_SUCCESS="GET_CHEF_WITH_ID_SUCCESS"
export const GET_CHEF_WITH_ID_FAILURE="GET_CHEF_WITH_ID_FAILURE"


export const SEARCH_FILTER="SEARCH_FILTER"

export const SEARCH_VIDEO_FILTER="SEARCH_VIDEO_FILTER"

export const VIDEO_POST_REQUEST="VIDEO_POST_REQUEST"
export const VIDEO_POST_SUCCESS="VIDEO_POST_SUCCESS"
export const VIDEO_POST_FAILURE="VIDEO_POST_FAILURE"


export const DELETE_VIDEO_REQUEST="DELETE_VIDEO_REQUEST"
export const DELETE_VIDEO_SUCCESS="DELETE_VIDEO_SUCCESS"
export const DELETE_VIDEO_FAILURE="DELETE_VIDEO_FAILURE"


export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCCESS="DELETE_USER_SUCCESS"
export const DELETE_USER_FAILURE="DELETE_USER_FAILURE"


export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const GET_USER_FAILURE="GET_USER_FAILURE"


export const FILTER_USERS="FILTER_USERS"