export const CHEF_REQUEST="CHEF_REQUEST"

export const CHEF_SUCCESS="CHEF_SUCCESS"

export const CHEF_FAILURE="CHEF_FAILURE"



export const GET_CHEF_WITH_ID_REQUEST="GET_CHEF_WITH_ID_REQUEST"
export const GET_CHEF_WITH_ID_SUCCESS="GET_CHEF_WITH_ID_SUCCESS"
export const GET_CHEF_WITH_ID_FAILURE="GET_CHEF_WITH_ID_FAILURE"


export const SEARCH_FILTER="SEARCH_FILTER"